### PR TITLE
Feature application and houses

### PR DESCRIPTION
**Pull request by LaansDole**
I don't know why my feature-houses branch disappear and merge with this branch

Update in Application:
resolve Application::init_database, Application::load_database, Application::save_database, Application::main_loop()

Update in house namespace:
add HouseRequests class
resove constructors for HosueRequest, HouseListing

### CODE REVIEW

**Review by ngocduan99 — DISMISSED** [review]

**Review by miketvo — COMMENTED** [review]
LGTM

**Review by miketvo — COMMENTED** [review]
LGTM

**Review by miketvo — DISMISSED** [review]
LGTM

**Review by ngocduan99 — DISMISSED** [review]

**Review by miketvo — APPROVED** [review]
LGTM again

**Review by namnguyen20999 — APPROVED** [review]
lgtm

**Pull request merged**
