### PR TITLE
Feature review

### PR DESCRIPTION
**Pull request by namnguyen20999**
* Adding `Review` parent class
* Adding` HouseReview.cpp` & `HouseReview.h`
* Adding` OccupantReview.cpp` & `OccupantReview.h`

### CODE REVIEW

**Review by LaansDole — DISMISSED** [review]
Create a default value in the constructor rather than having two constructors

**Review by miketvo — CHANGES_REQUESTED** [review]
Please leave a description for your PR next time, and you don't have to close #8 to open this PR, just use `git checkout .` if you want to reset your local work. Aside from that, there are a few big issues:


### 1. The namespaces are wrong:
- For `HouseReview` class, the namespace is `house`, not ~`HouseReview`~.
- For `OccupantReview` class, the namespace is `account`, not ~`OccupantReview`~.


### 2. Incorrect class attribute names:
- Change this to `reviewer` please:
image
- Change this to `reviewer, reviewee` (2 attributes) please:
image


### 3. Also, please create a new `Review` parent class for `HouseReview` and `OccupantReview` since both of them has these common attributes:

- `std::string id`
- `std::string comment`
- `int rating`

Put it in the `/src/utils folder`, and the namespace for it is `utils` (same namespace as my `DatabaseFile` class). I can update the UML for you if you think it's too complicated to do, because I know how to make it simple.


### 4. On a smaller note:

Next time you make feature branch, the naming format is `feature-review`, with dash, not `feature_review` with underscore. You don't have to change it now, just remember to do it for your future feature branches 😺

**Comment by miketvo** [comment]
Also:
- Please reindent line 19 in `OccupantReview.h` and line 21 in `HouseReview.h`
- (Best practices) On line 20 in `OccupantReview.h` and line 22 in `HouseReview.h`, add ` // <namespace_name>` at the end of the line, like on line 62 of `DatabaseFIle.h`:
image

**Comment by miketvo** [comment]
@namnguyen20999 You also created this branch from `main` instead of `dev`, please rebase this branch onto `dev`. If you don't know how to, let me know and I can do it for you, or give you the instructions if you want to do it yourself.

[Resolved ✅](https://github.com/miketvo/rmit2022c-eeet2482-lodging-app/pull/9/commits/e28240744ab330672878c85528d7062402697edb)

**Review by miketvo — APPROVED** [review]
LGTM

**Review by ngocduan99 — APPROVED** [review]

**Pull request merged**
